[package]
name = "keylogger"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
windows = { version = "0.57.0", features = ["Win32_UI_Input_KeyboardAndMouse", "Win32_UI_TextServices", "Win32_UI_WindowsAndMessaging"] }
